spring:
  application:
    name: "configServer"
  profiles:
    active: "git"
#    active: native # ????????
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config" # ?????????
#            search-locations: "file:/Users/kenny-sunhope/Documents/config" # ?????????
        git:
          uri: "https://github.com/kennyowj961127/SpringBootConfigServer.git" # ??git????
          default-label: "master" # ??git?????
          timeout: 5 # ??????
          clone-on-start: true # ??????????git???????
          force-pull: true # ????????git???????
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*" # ???????
encrypt:
  key: "45QDFAFSAFDAG456464GDSGSG"
server:
  port: 8071