spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071" # ?????????
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*" # ???????
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Gateway Server"
  description: "Gateway Server Service"
  version: "1.0.0"