services:
  accounstdb:
    container_name: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  loanstdb:
    container_name: loanstdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loanstdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  cardstdb:
    container_name: cardstdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: cardstdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  configserver:
    image: kennyowj961127/configserver:s7
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: kennyowj961127/accounts:s7
    container_name: accounts-ms
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accounstdb:3306/accountsdb"
    depends_on:
      accounstdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: kennyowj961127/loans:s7
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loanstdb:3306/loansdb"
    depends_on:
      loanstdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: kennyowj961127/cards:s7
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardstdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  backend:
    driver: "bridge"