spring:
  application:
    name: "configserver"
  profiles:
    active: "git"
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#            search-locations: "file:/Users/kenny-sunhope/Documents/config"
        git:
          uri: "https://github.com/kennyowj961127/SpringBootConfigServer.git"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
encrypt:
  key: "45QDFAFSAFDAG456464GDSGSG"
server:
  port: 8071