server:
  port: 8081
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071" # 指定配置文件的位置
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有的端点
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true

  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "accounts"
  description: "Accounts Service"
  version: "1.0.0"
logging:
  level:
    com:
      kenny:
        accounts: debug
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
  retry:
    configs:
      default:
        wait-duration: 500
        max-attempts: 3
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2.0
        ignore-exceptions:
          - java.lang.NullPointerException
  ratelimiter:
    configs:
      default:
        timeout-duration: 1000
        limit-for-period: 1
        limit-refresh-period: 5000
