server:
    port: 8090
spring:
    application:
      name: "loans"
    profiles:
      active: "prod"
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: ''
    h2:
        console:
          enabled: true
    jpa:
      show-sql: true
    sql:
      init:
        mode: always
    config:
      import: "optional:configserver:http://localhost:8071" # 指定配置文件的位置
    cloud:
      kubernetes:
        discovery:
          all-namespaces: true
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有的端点
    shutdown:
      enabled: true
  health:
    probes:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "loans"
  description: "Loans Service"
  version: "1.0.0"
logging:
  level:
    com:
      kenny:
        loans: debug
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"