server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071" # 指定配置文件的位置
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有的端点
    shutdown:
      enabled: true
  health:
    probes:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "cards"
  description: "Cards Service"
  version: "1.0.0"
logging:
  level:
    com:
      kenny:
        cards: debug